### ISSUE TITLE
Using composer for installation

### ISSUE THREAD

**Issue by Guidoexge** [Erkens/FPDF-Barcode#3]
Hi,

maybe my poor understanding, I can't install FPDF-Barcode using composer, simply the barcode class was not found. (all work correctly if I manually include the class).

Maybe I do something wrong, but I have only setasign/FPDF and FPDF-barcode installed with composer.

Have you any suggestions ?

Thanks, Guido

**Comment by erkens** [comment]
It works for me with composer?

Can you show your composer.json?

**Comment by Guidoexge** [comment]
this is composer.json 

{
    "name": "guido/wwwatb",
    "description": "Sito per la Gestione Operativa di ATB",
    "type": "library",
    "autoload": {
        "psr-4": {
            "Guido\\Wwwatb\\": "src/"
        }
    },
    "authors": [
        {
            "name": "Guido Valle",
            "email": "guido.valle@gmail.com"
        }
    ],
    "minimum-stability": "stable",
    "require": {
        "setasign/fpdf": "^1.8",
        "erkens/fpdf-barcode": "^2.1"
    }
}

as you seen, I only insert FPDF from setasign and your fpdf-barcode

**Comment by erkens** [comment]
You don't need to require setasign/fpdf explicite, but it should not matter. 
I just tested your composer.json file and I only need to escape your namespace (`\\` instead of `\`) and it worked flawless?
![image](https://github.com/erkens/FPDF-Barcode/assets/10248696/91c14f92-f484-4545-a712-e8125700d167)

```
{
  "name": "guido/wwwatb",
  "description": "Sito per la Gestione Operativa di ATB",
  "type": "library",
  "autoload": {
    "psr-4": {
      "Guido\\Wwwatb\\": "src/"
    }
  },
  "authors": [
    {
      "name": "Guido Valle",
      "email": "guido.valle@gmail.com"
    }
  ],
  "minimum-stability": "stable",
  "require": {
    "setasign/fpdf": "^1.8",
    "erkens/fpdf-barcode": "^2.1"
  }
}
```

![image](https://github.com/erkens/FPDF-Barcode/assets/10248696/ae0b2690-315c-465d-b172-42fa70ad67cd)

edit:
For this test I first used he an older `composer` docker image, which contains PHP 8.2.8 and Composer 2.5.8, but tested it now again with the most current `composer` docker image, which contains PHP 8.3.3 and Composer 2.7.1, results are the same.

**Comment by Guidoexge** [comment]
maybe the copy/paste modify double slash, it's also double.

I working on Win10 system with xampp, php 8.2.12 composer 2.7.1 

the code I use is this 👍 
require_once __DIR__ . '/../vendor/autoload.php';

//require_once('D:\htdocs\wwwatb\vendor\erkens\fpdf-barcode\src\Barcode.php');
//require_once('D:\htdocs\wwwatb\vendor\erkens\fpdf-barcode\src\Type\Code39.php');
$classes = get_included_files();
print_r($classes);
echo "<br>".__DIR__."<br>";
if (class_exists('FPDF')) { echo "<br>fpdf caricata<br>"; }
if (class_exists('Barcode')) { echo "<br>barcode caricata<br>"; }

and the result is that : 
Array ( [0] => D:\htdocs\wwwatb\etichette\stampa_etichetta.php [1] => D:\htdocs\wwwatb\funzioni.php [2] => D:\htdocs\wwwatb\funzioni_mysql.php [3] => D:\htdocs\wwwatb\local\config.php [4] => D:\htdocs\wwwatb\vendor\autoload.php [5] => D:\htdocs\wwwatb\vendor\composer\autoload_real.php [6] => D:\htdocs\wwwatb\vendor\composer\ClassLoader.php [7] => D:\htdocs\wwwatb\vendor\composer\autoload_static.php )
D:\htdocs\wwwatb\etichette

fpdf caricata

Fatal error: Uncaught Error: Class "Barcode" not found in D:\htdocs\wwwatb\etichette\stampa_etichetta.php:136 Stack trace: #0 {main} thrown in D:\htdocs\wwwatb\etichette\stampa_etichetta.php on line 136

Seems do not find fpdf-barcode

**Comment by erkens** [comment]
My guess is that it has to do something with the case-insentive filesystem from Windows, I don't have a Windows development environment to test this.

However it might also be a problem with the namespace, did you add `use Erkens\Fpdf\Barcode;` in the top of your PHP file?

**Comment by Guidoexge** [comment]
ok, it's only a use Erkens\Fpdf\Barcode; 

I don't use sorry, thanks for your help !
